name: tricommon
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.1
  flutter_localizations:
    sdk: flutter
  triinjector:
    git:
      url: https://github.com/IsaAmante/triinjector.git
      ref: v1.0.0
  provider: ^6.0.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.5
  timelines: ^0.1.0
  pin_code_fields: ^8.0.1
  intl: ^0.18.0
  mask_text_input_formatter: ^2.4.0
  money2: ^3.3.0
  cached_network_image: ^3.2.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  dio: ^5.1.2
  camera: ^0.10.0+3
  file_picker: ^5.2.2
  cpf_cnpj_validator: ^2.0.0
  unico_check: ^3.0.7
  fluttertoast: ^8.1.1
  package_info_plus: ^4.0.2
  geolocator: ^9.0.2
  lottie: ^2.2.0
  flutter_spinkit: ^5.1.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.5
  crypto: ^3.0.2
  flutter_image_compress: ^2.0.3
  share_plus: ^7.0.2
  collection: 1.17.1
  flutter_html: ^3.0.0-alpha.5
  external_app_launcher: ^3.1.0
  diacritic: ^0.1.3
  go_router: ^8.0.3
  qr_flutter: ^4.1.0
  device_info_plus: ^8.0.0
  js: ^0.6.7

  mocktail: ^0.3.0
  gallery_saver: ^2.3.2
  http_mock_adapter: ^0.4.4

  glassbox_flutter_plugin:
    hosted: https://glassbox.jfrog.io/artifactory/api/pub/pub-local-glassbox
    version: ^6.680.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: TribancoIcons
      fonts:
        - asset: assets/fonts/tribanco_icons.ttf

  assets:
    - assets/
    - assets/images/
    - assets/images/illustrations/
    - assets/images/credit_cards/
    - assets/images/camera/
    - assets/images/branding/
    - assets/images/symbol/
